version: '2.0'
services:
  db:
    image: postgres
    volumes:
    - ${DB_DATA_PATH}:/var/lib/postgresql/data
    environment:
    - TZ=Europe/Moscow
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    ports:
    - ${DB_PORT}:5432
    restart: always
  bot:
    build:
      context: .
      dockerfile: bot_Dockerfile
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - BOT_TOKEN=${BOT_TOKEN}
      - TG_PROXY_URL=${TG_PROXY_URL}
      - BOT_WORKERS=${BOT_WORKERS}
    restart: always
  console:
    build:
      context: .
      dockerfile: console_Dockerfile
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - BOT_TOKEN=${BOT_TOKEN}
      - TG_PROXY_URL=${TG_PROXY_URL}
      - CONSOLE_PORT=${CONSOLE_PORT}
      - CONSOLE_USERNAME=${CONSOLE_USERNAME}
      - CONSOLE_PASSWORD=${CONSOLE_PASSWORD}
    ports:
      - ${CONSOLE_PORT}:${CONSOLE_PORT}
    restart: always
